### ISSUE TITLE
A brief history about Time

### ISSUE THREAD

**Issue by IagoLast** [BarcelonaJS/talks#1]
### Talk Description

The upcoming release of the [Temporal API](https://tc39.es/proposal-temporal/docs/) brings a wave of anticipation, yet many of us are still unfamiliar with its [motivation](https://github.com/tc39/proposal-temporal#overview--motivation) and the reasons behind its potential impact.

This talk aims to provide a concise introduction to the history of calendars, shedding light on the context and significance of this proposal.

Humanity's long-standing collaborative project, the calendar, continues to present challenges in date and time zone management for many developers. Our exploration will span various historical methods of time measurement, from ancient solar calendars to the modern standards of ISO-8601, UTC and the Temporal API.

We'll delve into the quirks of our current calendar, such as why February has 28 days and why the months October, November, and December do not correspond to their numeric prefixes (Oct, Nov, Dec). We'll discuss how the advent of rail travel revolutionized timekeeping, the transition of time guardianship from astronomers to physicists, and the intriguing aspect of UNIX time where a second can vary in length, including the complications arising from this.

Concluding our historical journey, we will offer practical tips to help avoid common pitfalls in date handling, enhancing the understanding and anticipation of the Temporal API's introduction.

### Speaker Name

Iago Lastra Rodriguez

### Speaker Position

TimeTime.in cofounder

### Speaker LinkedIn

https://linkedin.com/in/iagolast

### Speaker Twitter

@iagolast

### Number of Talks Given Before

5+

### Speaker Company Name

TimeTime.in

### Speaker Company Website

www.timetime.in

### Speaker Company LinkedIn

https://www.linkedin.com/company/timetimeapp

### Speaker Company Twitter

https://twitter.com/timetime_in

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
@IagoLast ! Thanks for your submition. You have also been the first to try the new Form experience, how was it?

**Comment by IagoLast** [comment]
@onedesert It feels nice! Great job on this.

picky feedback: Maybe some speakers might not have twitter company. Maybe just a "company social media profile" would be more inclusive.

**Comment by onedesert** [comment]
Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by IagoLast** [comment]
I'm sorry @onedesert just saw this. 

can we make it feb/march ?

**Comment by onedesert** [comment]
Sure no problem, we have already fill up the January one.

**Comment by onedesert** [comment]
Hi again @IagoLast ! Would you be ready for the next meetup? https://github.com/BarcelonaJS/events/issues/54

**Comment by IagoLast** [comment]
@onedesert yep.

2024-02-29 right?

**Comment by onedesert** [comment]
Correct!

**Comment by onedesert** [comment]
@IagoLast as the oldest application you have been already assigned! https://github.com/BarcelonaJS/events/issues/54
