### ISSUE TITLE
Mission: Impossible - Performance Culture

### ISSUE THREAD

**Issue by andresz1** [BarcelonaJS/talks#12]
### Talk Description

Take a journey through our experience of improving web performance at [Fotocasa](https://fotocasa.es/es/), starting with a directive from top management to boost SEO. At first, it seemed like an impossible mission. Join me as I share the challenges, successes, and lessons learned along the way and learn how we managed to establish a culture focused on performance within the [company](https://adevinta.com/).

### Speaker Name

Andrés Alvarez

### Speaker Position

Staff Front-End Engineer

### Speaker LinkedIn

https://www.linkedin.com/in/aalvarezsordo

### Speaker Twitter

https://twitter.com/andresz_s

### Number of Talks Given Before

0

### Speaker Company Name

Adevinta

### Speaker Company Website

https://adevinta.com

### Speaker Company LinkedIn

https://www.linkedin.com/company/adevintaspain/mycompany/

### Speaker Company Twitter

https://twitter.com/adevintaspain

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by jordevo** [comment]
can't wait, sounds like an exciting talk! 👏

**Comment by onedesert** [comment]
Your talk submission is approved! We're excited to have you.
