### ISSUE TITLE
Leveraging CSS Paint API for Realistic Particle Animation

### ISSUE THREAD

**Issue by molefrog** [BarcelonaJS/talks#13]
### Talk Description

CSS Paint API isn't new, yet it's still an experimental web API for extending browser’s rendering engine. Using worklets, you can define custom CSS functions for drawing backgrounds, borders, custom gradients etc., in other words, things you would not be able to do with a regular Canvas. In this talk, we’ll use CSS Paint API to recreate a [Telegram-inspired spoiler animation](https://github.com/molefrog/spoiled). We will delve into the complexities related to the stateless nature of worklets, along with performance pros and cons.

A few facts about myself:
- Based in Copenhagen (still, would love to visit Barcelona)
- Previous talks - https://molefrog.com/speaking
- Currently, I am on a sabbatical break that I use to work on open-source and my own projects

### Speaker Name

Alexey Taktarov

### Speaker Position

Former Head of Engineering, founder at resume.io

### Speaker LinkedIn

https://www.linkedin.com/in/molefrog/

### Speaker Twitter

https://twitter.com/mlfrg

### Number of Talks Given Before

5+

### Speaker Company Name

Unemployed

### Speaker Company Website

https://molefrog.com

### Speaker Company LinkedIn

https://www.linkedin.com/in/molefrog/

### Speaker Company Twitter

https://twitter.com/mlfrg

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Thanks!

**Comment by dmitry-zaets** [comment]
Assigned instead of #10

**Comment by dmitry-zaets** [comment]
Assigned to https://github.com/BarcelonaJS/events/issues/60
