### ISSUE TITLE
Beyond Static — A Journey Through CSS, JavaScript and Web Animations API

### ISSUE THREAD

**Issue by iam-medvedev** [BarcelonaJS/talks#17]
### Talk Description

The web is constantly evolving and animations are no exception.
While simple animated transitions can be handled with standard techniques,
more complex, orchestrated animations require different approaches.
This talk will explore several animation techniques, including CSS animations,
JavaScript-driven animations and the Web Animations API.
We will delve into the technical details of each technique,
discuss their strengths and limitations and provide practical examples
to illustrate the nuances of working with complex animations.

### Speaker Name

Ilya Medvedev

### Speaker Position

CTO

### Speaker LinkedIn

https://linkedin.com/in/imedvedev

### Speaker Twitter

https://www.linkedin.com/in/imedvedev/

### Number of Talks Given Before

1-3

### Speaker Company Name

Readymag

### Speaker Company Website

https://readymag.com

### Speaker Company LinkedIn

https://linkedin.com/company/readymag

### Speaker Company Twitter

@readymag

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by dmitry-zaets** [comment]
Thank you!

**Comment by dmitry-zaets** [comment]
Hi, would you be willing to give a talk at our next meetup on 29th of October?

**Comment by iam-medvedev** [comment]
@dmitry-zaets sure!

**Comment by dmitry-zaets** [comment]
Cool, assigning you to the even then!
