### ISSUE TITLE
Introducing Brisa; new full-stack web framework

### ISSUE THREAD

**Issue by aralroca** [BarcelonaJS/talks#19]
### Talk Description

The idea is to present the [framework](https://brisa.build) that I started more than a year ago as a learning goal and now I finally make it public. Show a little of what it is about and encourage people to contribute to open-source.

### Speaker Name

Aral Roca Gomez

### Speaker Position

Software Engineer

### Speaker LinkedIn

https://www.linkedin.com/in/aral-roca-gomez-3b536bb1/

### Speaker Twitter

https://x.com/aralroca

### Number of Talks Given Before

1-3

### Speaker Company Name

Brisa

### Speaker Company Website

https://brisa.build

### Speaker Company LinkedIn

https://www.linkedin.com/in/aral-roca-gomez-3b536bb1/

### Speaker Company Twitter

https://x.com/brisadotbuild

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Thank you!

**Comment by dmitry-zaets** [comment]
Hi, would you be willing to give a talk at our next meetup on 29th of October?

**Comment by aralroca** [comment]
> Hi, would you be willing to give a talk at our next meetup on 29th of October?

Sure, I can do it without any problem.

**Comment by dmitry-zaets** [comment]
Great, Assigning you to the event.
