### ISSUE TITLE
The Wonders of Content Creation

### ISSUE THREAD

**Issue by bouwe77** [BarcelonaJS/talks#2]
### Talk Description

Hello,

I am Bouwe, a software engineer from The Netherlands, and visiting Barcelona between 18-23 January.

I have a talk called The Wonders of Content Creation (more info below) and was curious you happen to have a meetup during this time, and if you are looking for speakers?

So I would be available on every evening between 18-22 January, as I will be leaving on the 23rd.

It's a bit of a long shot, but you never know... 😄

Kind regards,
Bouwe

More about me, and my talk:

> "The Wonders of Content Creation" by Bouwe Westerdijk (https://bouwe.io)
> 
> As IT professionals, we consume a lot of content created by others. But are you also someone who creates content yourself? 
> 
> Content creation adds an extra dimension to your work as an IT professional. You can learn a lot from it, and it can give a boost to your career. However, many people don't do it. Why is that? It takes time, of course. And it can be quite daunting. 
> 
> In this session, Bouwe takes you into the wonderful world of content creation. Based on his own experiences, he answers questions like: Why should you create content? What can you achieve with it? And, of course: How do you start?
>
> So whether you're just starting or already creating content, let's experience the wondrous creative process of content creation together!

I gave this talk twice now, at 2 meetups in The Netherlands:

* December 2023: https://www.meetup.com/groningen/events/297332430/ (English)
* October 2023: https://www.meetup.com/groningen-frontend-devs/events/296030439/ (Dutch)

### Speaker Name

Bouwe Westerdijk

### Speaker Position

Software Engineer @ WebinarGeek 

### Speaker LinkedIn

https://www.linkedin.com/in/bkwesterdijk/

### Speaker Twitter

https://twitter.com/bouwe

### Number of Talks Given Before

5+

### Speaker Company Name

WebinarGeek

### Speaker Company Website

https://webinargeek.com

### Speaker Company LinkedIn

https://www.linkedin.com/company/webinargeek

### Speaker Company Twitter

https://twitter.com/webinargeek

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Hello! Thanks for your submit. We have a priority system based on issue submit time. But we can work it around as you will only be here for a period in January.
