### ISSUE TITLE
GraphQL - Resolvers + Typescript = Magic

### ISSUE THREAD

**Issue by a-chocolate-bear** [BarcelonaJS/talks#4]
### Talk Description

Building GraphQL servers can be frustrating and tedious. You have to write extra schema files, interfaces, and types for GraphQL fields and and arguments, write resolvers and then keep them in sync. You have to deal with type mismatches, typos, and refactoring issues.

TypeScript functions already have all the information we need to generate a complete GraphQL API (including the schema and resolvers) using type annotations and docblock hints. This forms a single source of truth and completely eliminates the need for redundant boilerplate code. It lets you leverage the power of type inference to build type safe GraphQL APIs.

In this demo, I will show you how to generate a complete GraphQL server using Hasura by writing only TypeScript functions that contain logic without building/writing API servers from scratch.

This talk will change the way you think about building APIs with TypeScript. 

### Speaker Name

Jesse Martin

### Speaker Position

Senior Sales Engineer

### Speaker LinkedIn

https://www.linkedin.com/in/jessedmartin/

### Speaker Twitter

https://twitter.com/motleydev

### Number of Talks Given Before

5+

### Speaker Company Name

Hasura

### Speaker Company Website

https://hasura.io/

### Speaker Company LinkedIn

https://www.linkedin.com/company/hasura

### Speaker Company Twitter

https://twitter.com/HasuraHQ

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Thanks for your submission.

**Comment by onedesert** [comment]
Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by a-chocolate-bear** [comment]
@onedesert Can I confirm by 15th Jan E.O.D?

**Comment by onedesert** [comment]
We had already assigned the talk for this month's event, we keep yours for future vents. We asked everyone, and we chose the oldest applicant that accepted.

**Comment by onedesert** [comment]
Hello again! I'm looking for available speakers for this month's event, https://github.com/BarcelonaJS/events/issues/54. As last time, the oldest to agree will be assigned, although this time we have 2 slots! Thanks in advance.

**Comment by a-chocolate-bear** [comment]
Hi @onedesert sorry for the late reply but it looks like you've already got speakers for this event. Please do let me know if you have a slot available for next month.

**Comment by dmitry-zaets** [comment]
hi @a-chocolate-bear we are planning the event for 30 of May (Thursday), are you available to give a talk? Thanks!
