### ISSUE TITLE
Develop dynamic React forms with ease (Formity)

### ISSUE THREAD

**Issue by martiserra99** [BarcelonaJS/talks#5]
### Talk Description

Formity is an npm package used to develop dynamic React forms with just a JSON. A dynamic form is a form of multiple steps in which the questions in each step depend on the answers provided in the previous ones. This talk aims to introduce this package to React developers and highlight its practical applications.

### Speaker Name

Martí Serra Molina

### Speaker Position

Full Stack Developer

### Speaker LinkedIn

https://www.linkedin.com/in/mart%C3%AD-serra-molina-3ababa23a/

### Speaker Twitter

https://twitter.com/MartSerraMolin1

### Number of Talks Given Before

0

### Speaker Company Name

-

### Speaker Company Website

-

### Speaker Company LinkedIn

-

### Speaker Company Twitter

-

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by martiserra99** [comment]
Yes, I am excited to present my talk this day.

Missatge de Yann Torres ***@***.***> del dia dc., 10 de gen.
2024 a les 10:16:

**Comment by onedesert** [comment]
Hello! This month's talk is set, but your submission is queued for next month. We follow a first-come basis and the oldest already confirmed. Stay tuned!

**Comment by onedesert** [comment]
Hello again! I'm looking for available speakers for this month's event, https://github.com/BarcelonaJS/events/issues/54. As last time, the oldest to agree will be assigned, although this time we have 2 slots! Thanks in advance.

**Comment by martiserra99** [comment]
I am available!

El dl., 5 de febr. 2024, 14:46, Yann Torres ***@***.***> va
escriure:

**Comment by onedesert** [comment]
Thanks so much! By Friday, I'll communicate the assigned talks, so everyone has time to reply.

**Comment by onedesert** [comment]
Hello! I'll assign you to the event!! Thanks! se you on the 29th.

**Comment by martiserra99** [comment]
Thank you, looking forward to it!

El ds., 10 de febr. 2024, 0:44, Yann Torres ***@***.***> va
escriure:
