### ISSUE TITLE
A Front-End Architecture that Makes Sense

### ISSUE THREAD

**Issue by fadamakis** [BarcelonaJS/talks#7]
### Talk Description

One of the most critical and challenging aspects of a large-scale application is a good and reasonable folder structure. The goal is to apply some kind of modularisation that will make the codebase easier to understand, set boundaries between features, and minimize code coupling and side effects. Let's explore an effective and scalable architecture together.

### Speaker Name

Fotis Adamakis

### Speaker Position

Senior Front End Engineer

### Speaker LinkedIn

https://www.linkedin.com/in/fadamakis/

### Speaker Twitter

https://twitter.com/fadamakis

### Number of Talks Given Before

3-5

### Speaker Company Name

- https://fadamakis.com/

### Speaker Company Website

- 

### Speaker Company LinkedIn

-

### Speaker Company Twitter

-

### Code of Conduct and Terms and Conditions

- [X] I accept the Code of Conduct and Terms and Conditions (Being Recorded)

**Comment by onedesert** [comment]
Thanks for your submission.

**Comment by onedesert** [comment]
Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by fadamakis** [comment]
Sure, I'm ready. Let me know if you need anything more from my side.

**Comment by onedesert** [comment]
Hello! This month's talk is set, but your submission is queued for next month. We follow a first-come basis and the oldest already confirmed. Stay tuned!

**Comment by dmitry-zaets** [comment]
hi @fadamakis we are planning the event for 30 of May (Thursday), are you available to give a talk? Thanks!

**Comment by fadamakis** [comment]
I'm available on 30/5. Thanks!

**Comment by dmitry-zaets** [comment]
Great, then confirming you!
